### ISSUE TITLE
Application Doesn't Submit in Front End

### ISSUE THREAD

**Issue by A1Liu** [bitcamp/bitcamp-site-2020#10]
The application submits to the backend and I receive an email for it, but there's no cooresponding indicator that I've submitted in the backend.

**Comment by eveninglily** [comment]
Thanks for the notice! This is a known issue, but it should be resolved, and your application should have been restored. Please let me know if you have any further issues!

**Comment by A1Liu** [comment]
Woohoo! Thanks!
